### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by j-corp-25**
Refactored birthdate, using age now, tested and data is working
Screenshot 2023-08-06 at 5 05 36 PM

### CODE REVIEW

**Comment by j-corp-25** [comment]
looks good to me

**Review by j-corp-25 — COMMENTED** [review]
yes

**Review by XLG123 — COMMENTED** [review]
when retrieving the user data from the database, the hashed passwords is returned?

**Review by j-corp-25 — COMMENTED** [review]
Thank you, i updated to account for this

**Review by XLG123 — APPROVED** [review]

**Comment by j-corp-25** [comment]
Hashpassword cant be seen anymore
Screenshot 2023-08-06 at 6 00 59 PM

**Pull request merged**
